/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OutputSplatRouteImport } from './routes/output/$'
import { Route as ApiSummarizeRouteImport } from './routes/api/summarize'
import { Route as ApiSummaryJobIdRouteImport } from './routes/api/summary/$jobId'
import { Route as ApiProgressJobIdRouteImport } from './routes/api/progress/$jobId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OutputSplatRoute = OutputSplatRouteImport.update({
  id: '/output/$',
  path: '/output/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSummarizeRoute = ApiSummarizeRouteImport.update({
  id: '/api/summarize',
  path: '/api/summarize',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSummaryJobIdRoute = ApiSummaryJobIdRouteImport.update({
  id: '/api/summary/$jobId',
  path: '/api/summary/$jobId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProgressJobIdRoute = ApiProgressJobIdRouteImport.update({
  id: '/api/progress/$jobId',
  path: '/api/progress/$jobId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/summarize': typeof ApiSummarizeRoute
  '/output/$': typeof OutputSplatRoute
  '/api/progress/$jobId': typeof ApiProgressJobIdRoute
  '/api/summary/$jobId': typeof ApiSummaryJobIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/summarize': typeof ApiSummarizeRoute
  '/output/$': typeof OutputSplatRoute
  '/api/progress/$jobId': typeof ApiProgressJobIdRoute
  '/api/summary/$jobId': typeof ApiSummaryJobIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/summarize': typeof ApiSummarizeRoute
  '/output/$': typeof OutputSplatRoute
  '/api/progress/$jobId': typeof ApiProgressJobIdRoute
  '/api/summary/$jobId': typeof ApiSummaryJobIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/summarize'
    | '/output/$'
    | '/api/progress/$jobId'
    | '/api/summary/$jobId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/summarize'
    | '/output/$'
    | '/api/progress/$jobId'
    | '/api/summary/$jobId'
  id:
    | '__root__'
    | '/'
    | '/api/summarize'
    | '/output/$'
    | '/api/progress/$jobId'
    | '/api/summary/$jobId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiSummarizeRoute: typeof ApiSummarizeRoute
  OutputSplatRoute: typeof OutputSplatRoute
  ApiProgressJobIdRoute: typeof ApiProgressJobIdRoute
  ApiSummaryJobIdRoute: typeof ApiSummaryJobIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/output/$': {
      id: '/output/$'
      path: '/output/$'
      fullPath: '/output/$'
      preLoaderRoute: typeof OutputSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/summarize': {
      id: '/api/summarize'
      path: '/api/summarize'
      fullPath: '/api/summarize'
      preLoaderRoute: typeof ApiSummarizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/summary/$jobId': {
      id: '/api/summary/$jobId'
      path: '/api/summary/$jobId'
      fullPath: '/api/summary/$jobId'
      preLoaderRoute: typeof ApiSummaryJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/progress/$jobId': {
      id: '/api/progress/$jobId'
      path: '/api/progress/$jobId'
      fullPath: '/api/progress/$jobId'
      preLoaderRoute: typeof ApiProgressJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiSummarizeRoute: ApiSummarizeRoute,
  OutputSplatRoute: OutputSplatRoute,
  ApiProgressJobIdRoute: ApiProgressJobIdRoute,
  ApiSummaryJobIdRoute: ApiSummaryJobIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
